import QueryProvider from '@/providers/QueryProvider';
import RecoilRootWrapper from '@/providers/RecoilRootWrapper';
import font from '@/styles/font';
import '@/styles/global.css';
import * as styles from './layout.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={font.className}>
      <body className={styles.container}>
        <RecoilRootWrapper>
          <QueryProvider>
            <div id="modal-portal" />
            <main>{children}</main>
          </QueryProvider>
        </RecoilRootWrapper>
      </body>
    </html>
  );
}
