import '@/styles/global.css';
import * as styles from './layout.css';
import font from '@/styles/font';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={font.className}>
      <body className={styles.container}>
        <div id="modal-portal" />
        <main>{children}</main>
      </body>
    </html>
  );
}
